### PR TITLE
If repo has too few commits, show all with git ll

### LINKED ISSUE #1: git ll fails with less than 3 commits
Attempting to use `git ll` on a repository with less than 3 commits fails with the message:

```
fatal: ambiguous argument 'master~3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This appears to be caused by b3e1bd0 and appears on [.gitconfig:23](https://github.com/phy1729/dotfiles/blob/master/.gitconfig#L23).

Of course, one could simply use `git lga` but it would be better for `lga` to be called automagically if `ll` fails.

### PR DESCRIPTION
**Pull request by m-wynn**
Unlike #2, this still attempts to do the old git ll.  However, in the
case that master has too few commits, this will instead show everything.
It is really simple and probably posix.

Fixes #1

### CODE REVIEW

**Comment by dinoocch** [comment]
This works for me :smile_cat:

**Comment by phy1729** [comment]
--name-only and --diff-filter are uesless here, but this seems to be a reasonable approach. Perhaps --max-parents=0 so the head call can be removed.

**Comment by m-wynn** [comment]
Better?

**Comment by phy1729** [comment]
You should figure out the correct way to handle repos like @dinoocch's ansible_ldap where there are multiple commits with no parents.

**Comment by m-wynn** [comment]
Is this something that happens often?

**Comment by phy1729** [comment]
Is a repo that has too few commits for ll something that happens often? If you're going to go down the rabbit hole of handling edge cases in code rather than using your head, you should handle all of the edge cases.

**Comment by m-wynn** [comment]
Every repo has too few commits for ll at some time or another.

**Comment by m-wynn** [comment]
Wouldn't the previous version of this commit work better for Dino's case?

**Pull request closed without merging**
